application: chromabrush
version: 1
runtime: python
api_version: 1

handlers:
- url: /image.*
  script: image.py

- url: /mocks/
  static_dir: mocks

- url: /audio/
  static_dir: frontend/audio
  mime_type: audio/ogg
  expiration: "6h"
  
- url: /css/
  static_dir: frontend/css

- url: /js/
  static_dir: frontend/js

- url: /img/
  static_dir: frontend/img
  expiration: "6h"

- url: /video/
  static_dir: frontend/video
  expiration: "6h"

- url: /
  script: server.py
  login: admin